#-------------------------------
# General Site Settings
title: Nullity - The quieter you become, the more you can hear
#logo: /images/Logo.png # You can add own logo. For example '/images/logo.png'.
logoTitle: Nullity
description: The quieter you become, the more you can hear
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://nullity.agharghar.com" # The base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# Author Settings
author:
  name: Nullity
  avatar: '/images/avatar.png'


#-------------------------------
# Hero Settings
hero:
  #title: Nullity
  description: Another Cybersecurity Blog ¯\_(ツ)_/¯
  image: '/images/01.jpg'


#-------------------------------
# Contact Settings
contact:
  email: f/xrbpzlew # Add your email for contact form
  descripti--forceon: Got a question, a project, or just want to discuss cybersecurity ? Feel free to reach out! Whether it's about penetration testing, security research, I'm always open to connecting. Just drop me a message, and I'll get back to you as soon as possible. # Add a description of your form

# NOTE
# Norlin theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
# - {icon: "ion-logo-twitter", link: "https://twitter.com/RazorSPoint"}
# - {icon: "ion-logo-youtube", link: "https://www.youtube.com/channel/UCzQ2vDjfscqSpXvSHhejJMg"}
# - {icon: "ion-logo-github", link: "https://github.com/SebastianSchuetze"}
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/zakariya-agharghar/"}


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: none-agharghar-com # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: G-1YRBCXPZ6M



#-------------------------------
# Newsletter
mailchimp: disable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-feed

kramdown:
  parse_block_html: true

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# # Archive
# jekyll-archives:
#   enabled: []
#   layout: archive
#   permalinks:
#     year: '/:year/'
#     month: '/:year/:month/'
#     day: '/:year/:month/:day/'
#     tag: '/tag/:name/'
#     category: '/category/:name/'


